app = "wishandwell"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "ewr"
swap_size_mb = 512

[build]
dockerfile = "/other/Dockerfile"
ignorefile = "/other/Dockerfile.dockerignore"

[experimental]
auto_rollback = true

  [experimental.attached]
  secrets = { }

[[mounts]]
destination = "/data"
source = "data"

[[services]]
internal_port = 8080
processes = [ "app" ]
protocol = "tcp"

  [services.concurrency]
  hard_limit = 100
  soft_limit = 80
  type = "requests"

  [[services.http_checks]]
  grace_period = "5s"
  interval = "10s"
  method = "get"
  path = "/resources/healthcheck"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

  [[services.http_checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/litefs/health"
  timeout = "5s"

  [[services.ports]]
  force_https = true
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  timeout = "2s"
